sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

services:
    - rabbitmq

before_install:
    - mkdir $PWD/bin
    - wget -O $PWD/bin/toxiproxy-server https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy-server-linux-amd64
    - chmod +x $PWD/bin/toxiproxy-server
    - export PATH=$PATH:$PWD/bin/

addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=py27-oldest-lib
  - TOX_ENV=py27-pinned-lib
  - TOX_ENV=py27-latest-lib
  - TOX_ENV=py27-mastereventlet-lib
  - TOX_ENV=py33-oldest-lib
  - TOX_ENV=py33-pinned-lib
  - TOX_ENV=py33-latest-lib
  - TOX_ENV=py33-mastereventlet-lib
  - TOX_ENV=py34-oldest-lib
  - TOX_ENV=py34-pinned-lib
  - TOX_ENV=py34-latest-lib
  - TOX_ENV=py34-mastereventlet-lib
  - TOX_ENV=py35-oldest-lib
  - TOX_ENV=py35-pinned-lib
  - TOX_ENV=py35-latest-lib
  - TOX_ENV=py35-mastereventlet-lib
  - TOX_ENV=py36-oldest-lib
  - TOX_ENV=py36-pinned-lib
  - TOX_ENV=py36-latest-lib
  - TOX_ENV=py36-mastereventlet-lib
  - TOX_ENV=pypy-oldest-lib
  - TOX_ENV=pypy-pinned-lib
  - TOX_ENV=pypy-latest-lib
  - TOX_ENV=pypy-mastereventlet-lib
  - TOX_ENV=py34-branchcoverage-lib
  - TOX_ENV=py27-examples
  - TOX_ENV=py34-examples
  - TOX_ENV=py35-examples
  - TOX_ENV=py36-examples
  - TOX_ENV=pypy-examples
  - TOX_ENV=docs

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-mastereventlet-lib
    - env: TOX_ENV=py33-mastereventlet-lib
    - env: TOX_ENV=py34-mastereventlet-lib
    - env: TOX_ENV=py35-mastereventlet-lib
    - env: TOX_ENV=py36-mastereventlet-lib
    - env: TOX_ENV=pypy-mastereventlet-lib
    - env: TOX_ENV=py34-branchcoverage-lib

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: Mwinp9cxGaGe/KjGFcO+T7MAgLvy5yFNeYCq9zpGniuSXsp/AFH3JIS1kWBv71tMC8S2N5kwRMVXoHNMqJt+Iq/EmYIY6vbMK8GijAUqLo8KsbxgmigWTXTn6IHKDO4gwYmQt8BDYJmbq6CNeVVCHMxWyP0Y24S25y7N35oIroU=
  on:
    tags: true
    repo: nameko/nameko
  distributions: "sdist bdist_wheel"
