sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "3.6"  # broken
  - "pypy"
  - "pypy3"

services:
    - rabbitmq

before_install:
    - mkdir $PWD/bin
    - wget -O $PWD/bin/toxiproxy-server https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy-server-linux-amd64
    - chmod +x $PWD/bin/toxiproxy-server
    - export PATH=$PATH:$PWD/bin/

addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox-travis

cache:
  directories:
    - $HOME/.cache/pip

env:
  - FACTOR=oldest
  - FACTOR=pinned
  - FACTOR=latest
  - FACTOR=mastereventlet

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: FACTOR=examples
    - python: 3.4
      env: FACTOR=examples
    - python: 3.4
      env: FACTOR=branchcoverage
    - python: 3.4
      env: FACTOR=docs

  allow_failures:
    - env: FACTOR=mastereventlet
    - python: 3.4
      env: FACTOR=branchcoverage
    - python: pypy3
      env: latest

script:
  - tox

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: Mwinp9cxGaGe/KjGFcO+T7MAgLvy5yFNeYCq9zpGniuSXsp/AFH3JIS1kWBv71tMC8S2N5kwRMVXoHNMqJt+Iq/EmYIY6vbMK8GijAUqLo8KsbxgmigWTXTn6IHKDO4gwYmQt8BDYJmbq6CNeVVCHMxWyP0Y24S25y7N35oIroU=
  on:
    tags: true
    repo: nameko/nameko
  distributions: "sdist bdist_wheel"
