sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services:
    - rabbitmq

before_install:
    - mkdir $PWD/bin
    - wget -O $PWD/bin/toxiproxy-server https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy-server-linux-amd64
    - chmod +x $PWD/bin/toxiproxy-server
    - export PATH=$PATH:$PWD/bin/

addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox-travis

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=oldest-lib
  - TOX_ENV=pinned-lib
  - TOX_ENV=latest-lib
  - TOX_ENV=mastereventlet-lib
  - TOX_ENV=py34-branchcoverage-lib
  - TOX_ENV=examples
  - TOX_ENV=py34-docs

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=mastereventlet-lib
    - env: TOX_ENV=branchcoverage-lib

script:
  - tox

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: Mwinp9cxGaGe/KjGFcO+T7MAgLvy5yFNeYCq9zpGniuSXsp/AFH3JIS1kWBv71tMC8S2N5kwRMVXoHNMqJt+Iq/EmYIY6vbMK8GijAUqLo8KsbxgmigWTXTn6IHKDO4gwYmQt8BDYJmbq6CNeVVCHMxWyP0Y24S25y7N35oIroU=
  on:
    tags: true
    repo: nameko/nameko
  distributions: "sdist bdist_wheel"
