sudo: false
language: python
python:
  - "2.7"

services:
    - rabbitmq

addons:
  apt_packages:
    - libenchant-dev

before_install:
  - wget -O toxiproxy-2.0.0.deb https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy_2.0.0_amd64.deb
  - sudo dpkg -i toxiproxy-2.0.0.deb

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOX_ENV=py27-oldest-lib
  - TOX_ENV=py27-pinned-lib
  - TOX_ENV=py27-latest-lib
  - TOX_ENV=py33-oldest-lib
  - TOX_ENV=py33-pinned-lib
  - TOX_ENV=py33-latest-lib
  - TOX_ENV=py34-oldest-lib
  - TOX_ENV=py34-pinned-lib
  - TOX_ENV=py34-latest-lib
  - TOX_ENV=py27-examples
  - TOX_ENV=py34-examples
  - TOX_ENV=docs

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: Mwinp9cxGaGe/KjGFcO+T7MAgLvy5yFNeYCq9zpGniuSXsp/AFH3JIS1kWBv71tMC8S2N5kwRMVXoHNMqJt+Iq/EmYIY6vbMK8GijAUqLo8KsbxgmigWTXTn6IHKDO4gwYmQt8BDYJmbq6CNeVVCHMxWyP0Y24S25y7N35oIroU=
  on:
    tags: true
    repo: onefinestay/nameko
  distributions: "sdist bdist_wheel"
